spring:
  application:
    name: ad-gateway
server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    #注册到eureka server
    service-url:
      defaultZone: http://localhost:8000/eureka/